Why does this code produce an error?

def execute(block)
  block.call
end

execute { puts "Hello from inside the execute method!" }


The parameter in the method does not use the '&' symbol, so it expects an argument instead of a proc.


